Back to having local variables.

diff --git a/src/mpi-start.in b/src/mpi-start.in
--- a/src/mpi-start.in
+++ b/src/mpi-start.in
@@ -102,7 +102,7 @@ dump_env () {
 #======================================================================
 mpi_start_find_mktemp () {
     MPI_START_MKTEMP=mktemp
-    tempfile=`$MPI_START_MKTEMP 2> /dev/null`
+    local tempfile=`$MPI_START_MKTEMP 2> /dev/null`
     if test $? -ne 0 ; then
         # BSD style mktemp
         MPI_START_MKTEMP="mktemp -t MPI_START"
@@ -242,30 +242,30 @@ mpi_start_execute_wrapper() {
         # we create a new wrapper for each execution so we can have more than
         # one MPI execution in a single mpi-start call (not sure if it has any use)
         mpi_start_mktemp
-        export CMD_WRAPPER=$MPI_START_TEMP_FILE
-        chmod +x $CMD_WRAPPER
-        cat $MPI_START_MPI_WRAPPER > $CMD_WRAPPER
-        OUTPUT=""
-        ERROR=""
-        INPUT=""
+        local cmd_wrapper=$MPI_START_TEMP_FILE
+        chmod +x $cmd_wrapper
+        cat $MPI_START_MPI_WRAPPER > $cmd_wrapper
+        local output=""
+        local error=""
+        local input=""
         if test "x${I2G_MPI_APPLICATION_STDOUT}" != "x" ; then
-            OUTPUT="> ${I2G_MPI_APPLICATION_STDOUT}"
+            output="> ${I2G_MPI_APPLICATION_STDOUT}"
         fi
         if test "x${I2G_MPI_APPLICATION_STDERR}" != "x" ; then
             if test "x${I2G_MPI_APPLICATION_STDOUT}" = "x${I2G_MPI_APPLICATION_STDERR}" ; then
-                ERROR="2>&1"
+                error="2>&1"
             else
-                ERROR="2> ${I2G_MPI_APPLICATION_STDERR}"
+                error="2> ${I2G_MPI_APPLICATION_STDERR}"
             fi
         fi
         if test "x${I2G_MPI_APPLICATION_STDIN}" != "x" ; then
-            INPUT="< ${I2G_MPI_APPLICATION_STDIN}"
+            input="< ${I2G_MPI_APPLICATION_STDIN}"
         fi 
-        echo "$* $OUTPUT $ERROR $INPUT" >> $CMD_WRAPPER
-        echo "exit \$?" >> $CMD_WRAPPER
-        $CMD_WRAPPER
+        echo "$* $output $error $input" >> $cmd_wrapper
+        echo "exit \$?" >> $cmd_wrapper
+        $cmd_wrapper
         err=$?
-        rm -f $CMD_WRAPPER
+        rm -f $cmd_wrapper
         return $err
     fi
 }
@@ -281,12 +281,12 @@ dummy_scheduler() {
     export MPI_START_HOSTFILE=$MPI_START_TEMP_FILE
     mpi_start_mktemp
     export MPI_START_HOST_SLOTS_FILE=$MPI_START_TEMP_FILE
-    myhost=`hostname`
-    slots=1
+    local myhost=`hostname`
+    local slots=1
     if test "x${MPI_DUMMY_SCH_SLOTS}" != "x" ; then
         slots=$MPI_DUMMY_SCH_SLOTS
     fi
-    n=$slots
+    local n=$slots
     while [ $n -ne 0 ]; do
         echo $myhost >> $MPI_START_MACHINEFILE
         n=`expr $n - 1`
@@ -397,12 +397,12 @@ mpi_start_scheduler_detector() {
             warn_msg "failed to source : $i"
         fi
 
-        scheduler=`basename $i .scheduler`
+        local scheduler=`basename $i .scheduler`
 
         # check if support for this kind of schedulers is supported
         debug_msg "checking for scheduler support : $scheduler"
         scheduler_available
-        result=$?
+        local result=$?
 
         if test "x$result" = "x0" ; then 
             info_msg "activate support for $scheduler"
@@ -456,12 +456,12 @@ mpi_start_darwin_core_detector() {
         warn_msg "Unable to detect number of cores per cpu, assuming 1"
         MPI_START_COREPERSOCKET=1
     fi
-    TOTALCPUS=`sysctl -n hw.ncpu`
+    local totalcpus=`sysctl -n hw.ncpu`
     if test $? -ne 0 ; then
         warn_msg "Unable to detect total number of cpus, assuming 1"
         MPI_START_SOCKETS=1
     else
-        MPI_START_SOCKETS=`expr $TOTALCPUS / $MPI_START_COREPERSOCKET`
+        MPI_START_SOCKETS=`expr $totalcpus / $MPI_START_COREPERSOCKET`
     fi  
 }
 
@@ -555,11 +555,11 @@ main() {
     fi
 
     MPI_TYPE=`echo $I2G_MPI_TYPE | tr "[:lower:]" "[:upper:]" | tr "-" "_"`
-    US=_
-    MPI_PREFIX="MPI_"
-    MPI_PATH_SUFFIX="_PATH"
-    MPI_MODULE_SUFFIX="_MODULES"
-    MPI_VERSION_SUFFIX="_VERSION"
+    local US=_
+    local MPI_PREFIX="MPI_"
+    local MPI_PATH_SUFFIX="_PATH"
+    local MPI_MODULE_SUFFIX="_MODULES"
+    local MPI_VERSION_SUFFIX="_VERSION"
 
     MPI_VERSION=
     if test "x$I2G_MPI_VERSION" != "x" ; then
@@ -622,7 +622,7 @@ main() {
     # call the MPI specific startup functions
     info_msg "call backend MPI implementation"
     mpi_start
-    result=$?
+    local result=$?
 
     exit $result
 }
