New export variable code.

diff --git a/src/mpi-start.in b/src/mpi-start.in
--- a/src/mpi-start.in
+++ b/src/mpi-start.in
@@ -25,6 +25,10 @@ MPI_START_MPI_PREFIX=""
 MPI_START_CLEANUP_FILES=""
 MPI_START_SCHEDULER=""
 MPI_START_NP=1
+# mpiexec params
+MPI_GLOBAL_PARAMS=""
+MPI_LOCAL_PARAMS=""
+declare -a MPI_START_JOB_ENV
 MPI_START_DUMMY_SCHEDULER=${MPI_START_DUMMY_SCHEDULER:-1}
 
 
@@ -121,6 +125,9 @@ mpi_start_find_mktemp () {
 #======================================================================
 mpi_start_mktemp () {
     MPI_START_TEMP_FILE=`$MPI_START_MKTEMP $*`
+    if test $? -ne 0 ; then
+        warn_msg "Unable to create temp file!"
+    fi
     MPI_START_CLEANUP_FILES="$MPI_START_TEMP_FILE $MPI_START_CLEANUP_FILES"
 }
 
@@ -154,14 +161,20 @@ mpi_start_activate_mpi () {
 # env variables
 #======================================================================
 mpi_start_create_wrapper() {
-    if test "x${MPI_START_MPI_WRAPPER}" = "x" ; then
-        mpi_start_mktemp
-        export MPI_START_MPI_WRAPPER=$MPI_START_TEMP_FILE
-        cat > $MPI_START_MPI_WRAPPER << EOF
+    mpi_start_mktemp
+    export MPI_START_MPI_WRAPPER=$MPI_START_TEMP_FILE
+    cat > $MPI_START_MPI_WRAPPER << EOF
 #!/bin/sh
 test "x\$I2G_MPI_START_TRACE" = "x1" && set -x
 EOF
-    fi
+    local vars=${#MPI_START_JOB_ENV[*]}
+    local index=0
+
+    while [ $index -lt $vars ]; do
+        echo "export ${MPI_START_JOB_ENV[$index]}" >> $MPI_START_MPI_WRAPPER
+        let "index = $index + 1"
+    done
+    chmod +x $MPI_START_MPI_WRAPPER
 }
 
 #======================================================================
@@ -172,15 +185,20 @@ EOF
 # rest of parameters: variable value 
 #======================================================================
 mpi_start_export_variable () {
-    mpi_start_create_wrapper
-    var_name=$1
-    shift
-    if test "x$*" != "x"; then  
-        echo "export $var_name=\"$*\"" >> $MPI_START_MPI_WRAPPER
+    local var_name
+    if [[ $1 == *=* ]] ; then
+        var_name=`echo $1 | cut -f1 -d"="`
     else
-        echo "export $var_name" >> $MPI_START_MPI_WRAPPER
+        var_name=$1
     fi
     export MPI_START_ENV_VARIABLES="$MPI_START_ENV_VARIABLES $var_name"
+    local var_value=$1
+    shift
+    if test "x$*" != "x"; then
+        MPI_START_JOB_ENV[${#MPI_START_JOB_ENV[*]}]="${var_value}="'"'${*}'"'
+    else
+        MPI_START_JOB_ENV[${#MPI_START_JOB_ENV[*]}]="$var_value"
+    fi
 }
 
 #======================================================================
@@ -239,12 +257,6 @@ mpi_start_execute_wrapper() {
         return $?
     else
         mpi_start_create_wrapper
-        # we create a new wrapper for each execution so we can have more than
-        # one MPI execution in a single mpi-start call (not sure if it has any use)
-        mpi_start_mktemp
-        local cmd_wrapper=$MPI_START_TEMP_FILE
-        chmod +x $cmd_wrapper
-        cat $MPI_START_MPI_WRAPPER > $cmd_wrapper
         local output=""
         local error=""
         local input=""
@@ -261,11 +273,10 @@ mpi_start_execute_wrapper() {
         if test "x${I2G_MPI_APPLICATION_STDIN}" != "x" ; then
             input="< ${I2G_MPI_APPLICATION_STDIN}"
         fi 
-        echo "$* $output $error $input" >> $cmd_wrapper
-        echo "exit \$?" >> $cmd_wrapper
-        $cmd_wrapper
+        echo "$* $output $error $input" >> $MPI_START_MPI_WRAPPER
+        echo "exit \$?" >> $MPI_START_MPI_WRAPPER
+        $MPI_START_MPI_WRAPPER
         err=$?
-        rm -f $cmd_wrapper
         return $err
     fi
 }
@@ -766,11 +777,7 @@ if test "$I2G_MPI_START_ENABLE_TESTING" != "TEST" ; then
                 ;;
             -x)
                 shift
-                if [[ $1 == *=* ]] ; then
-                    mpi_start_export_variable `echo $1 | cut -f1 -d"="` `echo $1 | cut -f2- -d"="`
-                else
-                    mpi_start_export_variable $1 
-                fi
+                mpi_start_export_variable $1 
                 shift
                 ;;
             -d)
